background {
    monitor =
    path = /home/kweber/Pictures/463865.jpg
    blur_passes = 1
    blur_size = 1
    brightness = .75
}
input-field {
    monitor =
    size = 300, 50
    position = 0, -100
    halign = center
    valign = center
}
