gesture swipe left 3 hyprctl dispatch workspace +1
gesture swipe right 3 hyprctl dispatch workspace -1
gesture swipe down 3 hyprctl dispatch togglefloating
gesture swipe up 3 hyprctl dispatch fullscreen
